version: '3.1'

services:
  web:
    container_name: django_social_container
    build:
      context: ./
      dockerfile: dockerfile
    command: gunicorn social.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "80"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: django_pass
    ports:
      - "5050:80"
  nginx:
    container_name: nginx_container
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web
  redis: # default port 6379
    container_name: redis_container
    image: redis
    # ports:
    #   - 6379:6379
    restart: always
    depends_on:
      - web
  # worker:
  #   restart: always
  #   build: 
  #     context: ./
  #   command: celery -A social worker -l INFO
  # beat: # default port 5555
  #   build: 
  #     context: ./
  #   command: celery -A social beat -l INFO
  # flower:
  #   build:
  #     context: ./
  #   command: celery -A social flower --port=5566
  #   ports:
  #     - "5566:5566"
    # expose:
    #   - "5566"



volumes:
  postgres_data:
  static_volume:
  media_volume: