# Generated by Django 4.0.4 on 2022-06-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chitter', '0002_tweets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'Tweets'},
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='time_create',
            new_name='created_at',
        ),
    ]
